-- КТ и мероприятия в enumerations
insert into enumerations (id, name, position, type, active, created_at, updated_at)
values ((select max(id)+1 from enumerations), 'Контр.точка', 4, 'TargetType', true, '2019-11-29', '2019-11-29');
insert into enumerations (id, name, position, type, active, created_at, updated_at)
values ((select max(id)+1 from enumerations),'Мероприятие', 5, 'TargetType', true, '2019-11-29', '2019-11-29');

-- in targets
delete from targets where type='TypedTarget';

-- Результаты
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оказание услуг (выполнение работ)', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание (реорганизация) организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение образовательных мероприятий', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Принятие нормативного правового (правового) акта', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждение документа', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение массовых мероприятий', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Благоустройство территории, ремонт объектов недвижимого имущества', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение информационно-коммуникационной кампании', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание Российской промышленной зоны за рубежом', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Приобретение товаров, работ, услуг', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечено привлечение квалифицированных кадров', (select id from enumerations where type='TargetType' and name='Результат'), '', '2019-11-29', '2019-11-29', true, 0, 'TypedTarget');

-- КТ
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оказание услуг (выполнение работ)', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Оказание услуг (выполнение работ)' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание (реорганизация) организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение образовательных мероприятий', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение образовательных мероприятий' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Принятие нормативного правового (правового) акта', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждение документа', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение массовых мероприятий', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение массовых мероприятий' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Благоустройство территории, ремонт объектов недвижимого имущества', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Благоустройство территории, ремонт объектов недвижимого имущества' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение информационно-коммуникационной кампании', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение информационно-коммуникационной кампании' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создание Российской промышленной зоны за рубежом', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Приобретение товаров, работ, услуг', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Приобретение товаров, работ, услуг' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечено привлечение квалифицированных кадров', (select id from enumerations where type='TargetType' and name='Контр.точка'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечено привлечение квалифицированных кадров' and type='TypedTarget' and type_id=(select id from enumerations where type='TargetType' and name='Результат')), 'TypedTarget');

-- мероприятия 1
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Земельный участок предоставлен заказчику', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для вида работ "строительство"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получены положительные заключения по результатам государственных экспертиз', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"; выделяется экспертиза проектной документации, историко- культурная экспертиза, экологическая экспертиза, экспертиза достоверности сметной стоимости', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получено разрешение на строительство', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Строительно-монтажные работы завершены', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование приобретено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение" ', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование установлено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование введено в эксплуатацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Техническая готовность объекта, %', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение", "техническое перевооружение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Заключение органа государственного строительного надзора получено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение", "техническое перевооружение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Объект недвижимого имущества введен в эксплуатацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Государственная регистрация права на объект недвижимого имущества произведена', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для вида работ "строительство"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Строительство (реконструкция, техническое перевооружение, приобретение) объекта недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

-- мероприятия 2
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждены (одобрены, сформированы) документы, необходимые для оказания услуги (выполнения работы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Оказание услуг (выполнение работ)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Для оказания услуги (выполнения работы) подготовлено материально-техническое (кадровое) обеспечение.', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Оказание услуг (выполнение работ)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Услуга оказана (работы выполнены)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Оказание услуг (выполнение работ)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--МЕРОПРИЯТИя 3
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Принято решение о создании (реорганизации) организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Осуществлена государственная регистрация организации', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только при создании (реорганизации) организации', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечена организация деятельности организации (структурного подразделения) (структура управления и кадры)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечена организация деятельности организации (структурного подразделения) (имущество, финансы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получены лицензии, соответствующие видам деятельности организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется в случае выполнения организацией лицензируемых видов деятельности', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (реорганизация) организации (структурного подразделения)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

-- мероприятия 4
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждены (одобрены, сформированы) документы, необходимые для оказания услуги (выполнения работы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение образовательных мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Для оказания услуги (выполнения работы) подготовлено материально-техническое (кадровое) обеспечение.', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение образовательных мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Услуга оказана (работы выполнены)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение образовательных мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

-- мероприятия 5
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведено исследование по вопросу формирования и (или) тематике акта', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'выделяются следующие виды актов: правовой акт органа исполнительной власти, нормативный правовой акт органа исполнительной власти, распоряжение Правительства Российской Федерации (высшего исполнительного органа государственной власти субъекта Российской Федерации), постановление Правительства Российской Федерации (высшего исполнительного органа государственной власти субъекта Российской Федерации), указ Президента Российской Федерации, распоряжение Президента Российской Федерации, закон, решение Евразийской экономической комиссии', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт разработан', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт согласован с заинтересованными органами и организациями', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт прошел независимую антикоррупционную экспертизу', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для следующих видов актов: правовой акт органа исполнительной власти, распоряжение Правительства Российской Федерации (высшего исполнительного органа государственной власти субъекта Российской Федерации), распоряжение Президента Российской Федерации, решение Евразийской экономической комиссии', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('На акт получены требуемые заключения органов власти', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для следующих видов актов: правовой акт органа исполнительной власти, решение Евразийской экономической комиссии ', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт внесен в высший исполнительный орган государственной власти', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется для следующих видов актов: распоряжение Правительства Российской Федерации (высшего исполнительного органа государственной власти субъекта Российской Федерации), постановление Правительства Российской Федерации (высшего исполнительного органа государственной власти субъекта Российской Федерации), распоряжение Президента Российской Федерации, указ Президента Российской Федерации, закон', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт рассмотрен и одобрен высшим исполнительным органом государственной власти', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется для следующих видов актов: распоряжение Президента Российской Федерации, указ Президента Российской Федерации, закон ', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт утвержден (подписан)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт прошел государственную регистрацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется для вида акта "нормативный правовой акт органа исполнительной власти" ', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Акт вступил в силу', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Принятие нормативного правового (правового) акта' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 6
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведено исследование по вопросу формирования и (или) тематике документа', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ разработан', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ разработан', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ утвержден (подписан)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ опубликован', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Утверждение документа' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 7
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждены (одобрены, сформированы) документы, необходимые для оказания услуги (выполнения работы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение массовых мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Для оказания услуги (выполнения работы) подготовлено материально-техническое (кадровое) обеспечение.', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение массовых мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Услуга оказана (работы выполнены)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение массовых мероприятий' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 8
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('В случае создания государственной информационной системы включает специальные контрольные точки для типа результата ""Принятие нормативного правового (правового) акта"', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Сформированы (утверждены) технические документы для создания (развития) информационно-телекоммуникационного сервиса (информационной системы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Создан (завершено развитие) информационно-телекоммуникационного сервис (а) (информационной системы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Информационно-телекоммуникационный сервис (информационная система) аттестован (а) и сертифицирован (а) по требованиям безопасности информации', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Информационно-телекоммуникационный сервис (информационная система) введен (а) в промышленную эксплуатацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание (развитие) информационно-телекоммуникационного сервиса (информационной системы)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 9
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждены (одобрены, сформированы) документы, необходимые для оказания услуги (выполнения работы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Благоустройство территории, ремонт объектов недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Для оказания услуги (выполнения работы) подготовлено материально-техническое (кадровое) обеспечение.', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Благоустройство территории, ремонт объектов недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Услуга оказана (работы выполнены)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Благоустройство территории, ремонт объектов недвижимого имущества' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 10
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Утверждены (одобрены, сформированы) документы, необходимые для оказания услуги (выполнения работы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение информационно-коммуникационной кампании' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Для оказания услуги (выполнения работы) подготовлено материально-техническое (кадровое) обеспечение.', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение информационно-коммуникационной кампании' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Услуга оказана (работы выполнены)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение информационно-коммуникационной кампании' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 11
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечена подготовка для утверждения паспорта федерального проекта (запроса на изменение паспорта федерального проекта) (в части результата федерального проекта)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечено заключение соглашений о реализации на территории субъекта Российской Федерации регионального проекта, обеспечивающего достижение целей, показателей и результатов соответствующего федерального проекта (в части результата федерального проекта)', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'Применяется для федеральных проектов, отдельные результаты реализации которых относятся к полномочиям субъектов Российской Федерации', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечен мониторинг исполнения соглашений о реализации на территории субъекта Российской Федерации регионального проекта, обеспечивающего достижение целей, показателей и результатов соответствующего федерального  роекта, обработка и формирование заключений на отчеты, представляемые участниками федерального проекта в рамках мониторинга реализации федерального проекта (результата федерального проекта)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечен мониторинг реализации о реализации федерального проекта сформирован (в части результата федерального проекта)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечение реализации федерального (регионального) проекта (результата федерального (регионального) проекта)' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 12
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведение научно-исследовательских (опытно-конструкторских) работ, реализация проекта внедрения новой информационной технологии зарегистрировано в органе научно-технической информации федерального органа исполнительной власти в сфере научной, научно-технической и инновационной деятельности', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Научно-исследовательская (опытно-конструкторская) работа проведена (разработаны алгоритмы и программы новой информационной технологии)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Отчет по научно-исследовательской и опытно-конструкторской работе (работке алгоритмов и программ) зарегистрирован в органе научно-технической информации федерального органа исполнительной власти в сфере научной, научно-технической и инновационной деятельности', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Проведение научно-исследовательских (опытно­конструкторских) работ, реализация проекта внедрения новой информационной технологии' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 13
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Земельный участок предоставлен заказчику', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для вида работ "строительство"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получены положительные заключения по результатам государственных экспертиз', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"; выделяется экспертиза проектной документации, историко- культурная экспертиза, экологическая экспертиза, экспертиза достоверности сметной стоимости', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получено разрешение на строительство', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Строительно-монтажные работы завершены', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для видов работ "строительство", "реконструкция"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование приобретено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение" ', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование установлено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Оборудование введено в эксплуатацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Техническая готовность объекта, %', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение", "техническое перевооружение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Заключение органа государственного строительного надзора получено', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'не применяется для вида работ "приобретение", "техническое перевооружение"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Объект недвижимого имущества введен в эксплуатацию', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Государственная регистрация права на объект недвижимого имущества произведена', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только для вида работ "строительство"', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
--+
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Принято решение о создании (реорганизации) организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Осуществлена государственная регистрация организации', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется только при создании (реорганизации) организации', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечена организация деятельности организации (структурного подразделения) (структура управления и кадры)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Обеспечена организация деятельности организации (структурного подразделения) (имущество, финансы)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Получены лицензии, соответствующие видам деятельности организации (структурного подразделения)', (select id from enumerations where type='TargetType' and name='Мероприятие'), 'применяется в случае выполнения организацией лицензируемых видов деятельности', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
--+
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Проведено исследование по вопросу формирования и (или) тематике документа', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ разработан', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ разработан', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ утвержден (подписан)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Документ опубликован', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Создание Российской промышленной зоны за рубежом' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');

--мероприятия 15
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Определена потребность в работниках (персонале) различных категорий и квалификации', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечено привлечение квалифицированных кадров' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Определены источники привлечения необходимой численности работников (персонала) (скорректированы контрольные цифры приема для специалистов с высшим образованием и объемов подготовки для специалистов со средним профессиональным образованием, переподготовки граждан по востребованным направлениям, задание на переподготовку граждан)', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечено привлечение квалифицированных кадров' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Приняты меры по трудоустройству работников на вакантные рабочие места', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечено привлечение квалифицированных кадров' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
insert into targets (name, type_id, comment, created_at, updated_at, is_approve, parent_id, type) values('Созданы условия по закреплению привлеченных работников (персонала) на рабочих местах', (select id from enumerations where type='TargetType' and name='Мероприятие'), '', '2019-11-29', '2019-11-29', true, (select id from targets where name='Обеспечено привлечение квалифицированных кадров' and type_id=(select id from enumerations where type='TargetType' and name='Контр.точка')), 'TypedTarget');
